[general]
height = 700.0
keySize = 70.0
barSpeed = 600.0
backgroundColor = "0,0,0,255"
margin = 25.0
outlineThickness = 5.0
fading = true
counter = true
fps = 60
logToFile = false

[[key]]
name = "Z"
color = "255,0,0,255"
size = 1.0

[[key]]
name = "X"
color = "0,255,255,255"
size = 1.0
